"use client"

import { useState } from "react"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Button } from "@/components/ui/button"

export function HippaDisclaimerModal({ onAccept }: { onAccept: () => void }) {
  const [open, setOpen] = useState(true)

  const handleAccept = () => {
    setOpen(false)
    onAccept()
  }

  return (
    <Dialog open={open}>
      <DialogContent
        className="w-[90vw] max-w-5xl aspect-video flex flex-col overflow-hidden rounded-xl p-0"
        aria-describedby={undefined}
      >
        {/* Header */}
        <DialogHeader className="border-b bg-emerald-700 text-white rounded-t-xl px-6 py-3 flex-shrink-0">
          <DialogTitle>HIPAA Notice of Privacy Practices</DialogTitle>
        </DialogHeader>

        {/* 16:9 Scrollable Text Area */}
        <div className="relative flex-1 bg-white overflow-hidden">
          <ScrollArea className="h-full px-6 py-4 text-sm leading-relaxed space-y-4 text-gray-800">
            <p><strong>NORTH FALMOUTH PHARMACY</strong></p>
            <p><strong>NOTICE OF PRIVACY PRACTICES</strong></p>

            <p>
              This notice describes how medical information about you may be used and disclosed and how you can get access 
              to this information. Please review it carefully. If you have any questions about this Notice, please contact 
              North Falmouth Pharmacy at (508) 564-4459.
            </p>

            <h3 className="font-semibold text-emerald-700 mt-4">OUR PLEDGE REGARDING MEDICAL INFORMATION:</h3>
            <p>
              We understand that medical information about you and your health is personal. We are committed to protecting 
              medical information about you. We create a record of the care and services you receive at this pharmacy. We 
              need this record to provide you with quality care and to comply with certain legal requirements. This Notice 
              applies to all of the records of your care generated by this pharmacy, whether made by our personnel or 
              your personal doctor.
            </p>

            <h3 className="font-semibold text-emerald-700 mt-4">WE ARE REQUIRED BY LAW TO:</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Make sure that medical information that identifies you is kept private.</li>
              <li>Give you this Notice of our legal duties and privacy practices with respect to medical information about you.</li>
              <li>Follow the terms of the Notice that is currently in effect.</li>
            </ul>

            <h3 className="font-semibold text-emerald-700 mt-4">HOW WE MAY USE AND DISCLOSE MEDICAL INFORMATION ABOUT YOU:</h3>
            <p>
              The following categories describe different ways that we use and disclose medical information. For each 
              category of uses or disclosures, we will explain what we mean and try to give some examples.
            </p>

            <h4 className="font-medium mt-3">For Treatment</h4>
            <p>
              We may use medical information about you to provide you with medical treatment or services. We may disclose 
              medical information about you to doctors, nurses, technicians, or other pharmacy personnel who are involved 
              in taking care of you.
            </p>

            <h4 className="font-medium mt-3">For Payment</h4>
            <p>
              We may use and disclose medical information about you so that the treatment and services you receive at the 
              pharmacy may be billed to and payment may be collected from you, an insurance company, or a third party.
            </p>

            <h4 className="font-medium mt-3">For Health Care Operations</h4>
            <p>
              We may use and disclose medical information about you for pharmacy operations. These uses and disclosures are 
              necessary to run the pharmacy and make sure that all of our patients receive quality care.
            </p>

            <h3 className="font-semibold text-emerald-700 mt-4">OTHER USES OF MEDICAL INFORMATION</h3>
            <p>
              Other uses and disclosures of medical information not covered by this Notice or the laws that apply to us will 
              be made only with your written permission. If you provide us permission to use or disclose medical information 
              about you, you may revoke that permission, in writing, at any time.
            </p>

            <h3 className="font-semibold text-emerald-700 mt-4">YOUR RIGHTS REGARDING MEDICAL INFORMATION ABOUT YOU</h3>
            <ul className="list-disc pl-6 space-y-2">
              <li>Right to Inspect and Copy — You have the right to inspect and copy medical information that may be used to make decisions about your care.</li>
              <li>Right to Amend — If you feel that medical information we have about you is incorrect or incomplete, you may ask us to amend the information.</li>
              <li>Right to Accounting of Disclosures — You have the right to request a list of the disclosures we made of medical information about you.</li>
              <li>Right to Request Restrictions — You have the right to request a restriction or limitation on the medical information we use or disclose.</li>
              <li>Right to Request Confidential Communications — You have the right to request that we communicate with you about medical matters in a certain way.</li>
              <li>Right to a Paper Copy of This Notice — You may ask us for a paper copy of this Notice at any time.</li>
            </ul>

            <h3 className="font-semibold text-emerald-700 mt-4">CHANGES TO THIS NOTICE</h3>
            <p>
              We reserve the right to change this Notice and make the revised or changed Notice effective for medical 
              information we already have about you as well as any information we receive in the future.
            </p>

            <h3 className="font-semibold text-emerald-700 mt-4">COMPLAINTS</h3>
            <p>
              If you believe your privacy rights have been violated, you may file a complaint with the pharmacy or with the 
              Secretary of the Department of Health and Human Services. To file a complaint with the pharmacy, contact North 
              Falmouth Pharmacy, 111 County Road, North Falmouth, MA 02556. You will not be penalized for filing a complaint.
            </p>
          </ScrollArea>
        </div>

        {/* Footer */}
        <DialogFooter className="border-t bg-gray-50 px-6 py-4 flex-shrink-0 justify-end">
          <Button
            onClick={handleAccept}
            className="bg-emerald-700 hover:bg-emerald-800 text-white rounded-full px-6"
          >
            I Acknowledge and Agree
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}